import asyncio
import uuid
from src.db.session import async_session_maker
from src.db.models import (
    Report,
    ReportSection,
    Source,
    ReportSource,
    AgentRun,
    AgentRole,
    AgentRunStatus,
    AgentTask,
    AgentTaskStatus,
)
from src.db.repository import ReportRepository, SourceRepository, AgentRunRepository


async def test_repos() -> None:
    print("\n--- Testing Repositories ---")
    async with async_session_maker() as session:
        report_repo = ReportRepository(session)
        source_repo = SourceRepository(session)
        agent_repo = AgentRunRepository(session)

        # 1. Fetch any existing report
        reports = await report_repo.list(limit=1)
        assert len(reports) > 0, "No reports found from seeding!"
        report = reports[0]
        print(f"[OK] ReportRepository.list returned report: {report.id} (status: {report.status.value})")

        # 2. Add a section
        section = ReportSection(
            id=uuid.uuid4(),
            report_id=report.id,
            heading="Executive Summary",
            content="This is the executive summary generated by the multi-agent system.",
            order_index=1,
        )
        session.add(section)
        await session.flush()
        print(f"[OK] Added ReportSection: {section.heading} (id: {section.id})")

        # 3. Create a source with pgvector embedding (1536 dimensions)
        sample_embedding = [0.01 * (i % 10) for i in range(1536)]
        source = await source_repo.create(
            url=f"https://arxiv.org/abs/2609.{uuid.uuid4().hex[:6]}",
            title="Consensus in Autonomous Multi-Agent Networks",
            embedding=sample_embedding,
        )
        print(f"[OK] SourceRepository.create created source: {source.title} with 1536-dim embedding")

        # 4. Link report and source
        report_source = ReportSource(
            report_id=report.id,
            source_id=source.id,
            cited_in_section_id=section.id,
        )
        session.add(report_source)
        await session.flush()
        print(f"[OK] Linked Report and Source via ReportSource association")

        # 5. Test ReportRepository.get_with_sections (eager loading)
        loaded_report = await report_repo.get_with_sections(report.id)
        assert loaded_report is not None
        assert len(loaded_report.sections) >= 1
        assert len(loaded_report.report_sources) >= 1
        assert loaded_report.report_sources[0].source is not None
        print(f"[OK] ReportRepository.get_with_sections verified eager loading:")
        print(f"     - Sections count: {len(loaded_report.sections)}")
        print(f"     - Eager loaded section: '{loaded_report.sections[0].heading}'")
        print(f"     - Associated source: '{loaded_report.report_sources[0].source.title}'")

        # 6. Test SourceRepository.find_similar
        similar_sources = await source_repo.find_similar(sample_embedding, limit=3)
        assert len(similar_sources) >= 1
        print(f"[OK] SourceRepository.find_similar returned {len(similar_sources)} sources using pgvector cosine distance")

        # 7. Test AgentRunRepository
        run = await agent_repo.create(
            report_id=report.id,
            agent_role=AgentRole.ORCHESTRATOR,
            status=AgentRunStatus.RUNNING,
        )
        task = AgentTask(
            id=uuid.uuid4(),
            agent_run_id=run.id,
            task_type="plan_generation",
            status=AgentTaskStatus.RUNNING,
            payload={"focus_areas": ["consensus", "scalability"]},
        )
        session.add(task)
        await session.flush()

        loaded_run = await agent_repo.get_with_tasks(run.id)
        assert loaded_run is not None
        assert len(loaded_run.tasks) == 1
        print(f"[OK] AgentRunRepository.get_with_tasks verified: run {loaded_run.id} has {len(loaded_run.tasks)} task(s)")

        await session.commit()
        print("\n[SUCCESS] All repository tests passed successfully!")


if __name__ == "__main__":
    asyncio.run(test_repos())
