"use client";

import React, { useMemo, useState } from "react";
import { motion, useReducedMotion } from "framer-motion";
import {
  BookOpen,
  Copy,
  Download,
  ExternalLink,
  MessageSquare,
  Printer,
  Sparkles,
  Check,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useToast } from "@/components/ui/toast";
import { ReportDetailResponse, SourceResponse } from "@/lib/api-client";
import { ReportChatDrawer } from "@/components/report/report-chat-drawer";

interface ReportViewProps {
  report: ReportDetailResponse;
}

// Inline Citation Parser: Replaces [1], [2], [3] with interactive anchor links
function renderTextWithCitations(text: string) {
  const parts = text.split(/(\[\d+\])/g);

  return parts.map((part, index) => {
    const match = part.match(/\[(\d+)\]/);
    if (match) {
      const citationIndex = match[1];
      return (
        <a
          key={`cite-${index}`}
          href={`#source-${citationIndex}`}
          className="inline-flex items-center mx-0.5 px-1.5 py-0.2 rounded-xs text-[11px] font-mono font-semibold bg-accent/15 text-accent border border-accent/25 hover:bg-accent/25 hover:underline transition-all cursor-pointer select-none"
          title={`Jump to Source [${citationIndex}]`}
        >
          [{citationIndex}]
        </a>
      );
    }
    return part;
  });
}

export function ReportView({ report }: ReportViewProps) {
  const { toast } = useToast();
  const shouldReduceMotion = useReducedMotion();
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Sort sections strictly by order_index
  const sortedSections = useMemo(() => {
    const list = [...(report.sections || [])];
    return list.sort((a, b) => a.order_index - b.order_index);
  }, [report.sections]);

  const sources: SourceResponse[] = report.sources || [];

  const generateMarkdown = () => {
    return [
      `# ${report.query}`,
      "",
      `> **Quorum Research Report** | Generated on ${new Date(
        report.created_at
      ).toLocaleDateString()} | Status: ${report.status}`,
      "",
      ...sortedSections.flatMap((s) => [
        `## ${s.heading}`,
        "",
        s.content,
        "",
      ]),
      "## Sources & Verified Literature",
      "",
      ...sources.map(
        (src, idx) =>
          `[${idx + 1}] **${src.title || "Primary Source"}** - [${src.url}](${src.url})`
      ),
      "",
      "---",
      "_Generated by Quorum Multi-Agent Autonomous Research Platform._",
    ].join("\n");
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({
      title: "Markdown Copied",
      description: "Complete verified report copied to clipboard.",
      variant: "success",
    });
  };

  const handleDownloadMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    const safeName = report.query
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .slice(0, 40);
    link.href = url;
    link.download = `quorum-report-${safeName || report.id}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast({
      title: "Download Started",
      description: "Report downloaded in Markdown format.",
      variant: "success",
    });
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <>
      <motion.div
        initial={shouldReduceMotion ? { opacity: 0 } : { opacity: 0, y: 30 }}
        animate={shouldReduceMotion ? { opacity: 1 } : { opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="space-y-6 pt-4"
      >
        {/* Report Header Card */}
        <Card className="border border-border bg-surface shadow-sm overflow-hidden">
          <div className="bg-gradient-to-r from-accent/10 via-accent/5 to-transparent p-6 border-b border-border">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="space-y-2">
                <div className="flex items-center gap-2">
                  <Badge variant="complete" dot>
                    Verified Synthesis
                  </Badge>
                  <span className="text-xs font-mono text-text-secondary">
                    {sortedSections.length} Sections • {sources.length} Sources
                  </span>
                </div>
                <h2 className="text-xl md:text-2xl font-bold tracking-tight text-text-primary">
                  {report.query}
                </h2>
                <p className="text-xs text-text-secondary">
                  Synthesized by Quorum Orchestration Swarm • Cross-verified by Fact Checker
                </p>
              </div>

              {/* Action Toolbar */}
              <div className="flex items-center flex-wrap gap-2">
                <Button
                  variant="default"
                  size="sm"
                  onClick={() => setIsChatOpen(true)}
                  className="text-xs gap-1.5 bg-accent text-accent-contrast hover:opacity-90 shadow-xs"
                >
                  <MessageSquare className="h-3.5 w-3.5" />
                  Ask Swarm
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleCopyMarkdown}
                  className="text-xs gap-1.5"
                >
                  {copied ? (
                    <Check className="h-3.5 w-3.5 text-emerald-500" />
                  ) : (
                    <Copy className="h-3.5 w-3.5" />
                  )}
                  {copied ? "Copied" : "Copy Markdown"}
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleDownloadMarkdown}
                  className="text-xs gap-1.5"
                >
                  <Download className="h-3.5 w-3.5" />
                  Download .md
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handlePrint}
                  className="text-xs gap-1.5"
                >
                  <Printer className="h-3.5 w-3.5" />
                  Print / PDF
                </Button>
              </div>
            </div>
          </div>

          {/* Quick Prompt Helper Banner */}
          <div className="px-6 py-2.5 bg-surface-subtle/50 border-b border-border/60 flex items-center justify-between gap-3 text-xs">
            <div className="flex items-center gap-2 text-text-secondary">
              <Sparkles className="h-3.5 w-3.5 text-accent shrink-0" />
              <span>
                Want deeper analysis or section breakdown? Interact directly with the research swarm.
              </span>
            </div>
            <button
              onClick={() => setIsChatOpen(true)}
              className="text-xs font-medium text-accent hover:underline shrink-0"
            >
              Open Research Chat →
            </button>
          </div>

          {/* Report Sections Content */}
          <CardContent className="p-6 md:p-8 space-y-8 print:p-0">
            {sortedSections.length === 0 ? (
              <div className="text-center py-8 text-sm text-text-secondary">
                Report sections are being compiled by the Writer Agent...
              </div>
            ) : (
              sortedSections.map((section, idx) => (
                <motion.article
                  key={section.id || idx}
                  initial={shouldReduceMotion ? {} : { opacity: 0, y: 12 }}
                  animate={shouldReduceMotion ? {} : { opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.1, duration: 0.4 }}
                  className="space-y-3 prose dark:prose-invert max-w-none print:break-inside-avoid"
                >
                  <div className="flex items-center gap-3">
                    <span className="flex h-6 w-6 items-center justify-center rounded-control bg-accent/10 text-xs font-mono font-bold text-accent print:border print:border-text-secondary">
                      0{section.order_index}
                    </span>
                    <h3 className="text-lg font-semibold text-text-primary m-0 tracking-tight">
                      {section.heading}
                    </h3>
                  </div>

                  <div className="text-sm md:text-base leading-relaxed text-text-secondary pl-9">
                    <p className="whitespace-pre-line m-0">
                      {renderTextWithCitations(section.content)}
                    </p>
                  </div>
                </motion.article>
              ))
            )}
          </CardContent>
        </Card>

        {/* Sources & Verified Literature Panel */}
        <Card id="sources" className="border border-border bg-surface shadow-xs scroll-mt-20 print:break-inside-avoid">
          <CardHeader className="py-4 px-6 border-b border-border flex flex-row items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="flex h-6 w-6 items-center justify-center rounded-control bg-emerald-500/15 text-emerald-500">
                <BookOpen className="h-3.5 w-3.5" />
              </div>
              <div>
                <CardTitle className="text-base font-semibold text-text-primary">
                  Cited Sources & Academic Literature
                </CardTitle>
              </div>
            </div>

            <Badge variant="outline" className="text-xs font-mono">
              {sources.length} Primary References
            </Badge>
          </CardHeader>

          <CardContent className="p-6">
            <div className="divide-y divide-border/60">
              {sources.map((src, index) => {
                const citationNumber = index + 1;
                return (
                  <div
                    key={src.id || src.url}
                    id={`source-${citationNumber}`}
                    className="py-3 first:pt-0 last:pb-0 flex items-start justify-between gap-4 group transition-colors hover:bg-surface-subtle/50 rounded-control p-2 -mx-2"
                  >
                    <div className="flex items-start gap-3 min-w-0">
                      <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded text-xs font-mono font-bold bg-accent/15 text-accent border border-accent/25 mt-0.5">
                        [{citationNumber}]
                      </span>

                      <div className="space-y-0.5 min-w-0">
                        <h4 className="text-xs md:text-sm font-medium text-text-primary truncate">
                          {src.title || src.url}
                        </h4>
                        <p className="text-[11px] font-mono text-text-secondary truncate">
                          {src.url}
                        </p>
                      </div>
                    </div>

                    <a
                      href={src.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="flex items-center gap-1 text-xs font-medium text-accent hover:underline shrink-0 pt-1 print:hidden"
                    >
                      <span>View Source</span>
                      <ExternalLink className="h-3.5 w-3.5" />
                    </a>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </motion.div>

      {/* Ask the Swarm Drawer */}
      <ReportChatDrawer
        isOpen={isChatOpen}
        onClose={() => setIsChatOpen(false)}
        reportId={report.id}
        reportQuery={report.query}
      />
    </>
  );
}
